import { test, expect, activate, createRoutine, addAssignment, expectProgress, expectNoOverflow, captureReview } from '../helpers.js'
import { accounts, installProvider } from './provider.js'

test('Spanish account forms, provider errors and import summary survive sign-in and logout', async ({ page, context }, testInfo) => {
  await installProvider(context)
  await page.goto('/login')
  await activate(page, page.getByRole('button', { name: 'Switch to Spanish', exact: true }))
  await page.getByLabel('Correo electrónico', { exact: true }).fill(accounts.a.email)
  await page.getByLabel('Contraseña', { exact: true }).fill('wrong-password')
  await activate(page, page.getByRole('button', { name: 'Iniciar sesión', exact: true }))
  await expect(page.getByRole('alert')).toContainText('El correo o la contraseña son incorrectos.')
  await expect(page.getByLabel('Contraseña', { exact: true })).toHaveValue('wrong-password')
  await activate(page, page.getByRole('link', { name: 'Crear una cuenta', exact: true }))
  await expect(page.getByRole('heading', { name: 'Creá tu cuenta', exact: true })).toBeVisible()
  await page.getByLabel('Correo electrónico', { exact: true }).fill(accounts.b.email)
  await page.getByLabel('Contraseña', { exact: true }).fill('password-123')
  await activate(page, page.getByRole('button', { name: 'Crear cuenta', exact: true }))
  await expect(page.getByText('Las contraseñas deben coincidir.', { exact: true })).toBeVisible()
  await page.getByLabel('Confirmar contraseña', { exact: true }).fill('password-123')
  await activate(page, page.getByRole('button', { name: 'Crear cuenta', exact: true }))
  await expect(page.getByRole('status').filter({ hasText: 'Revisá tu correo para confirmar la cuenta' })).toBeVisible()
  await page.goto('/forgot-password')
  await page.getByLabel('Correo electrónico', { exact: true }).fill(accounts.a.email)
  await activate(page, page.getByRole('button', { name: 'Enviar correo de recuperación', exact: true }))
  await expect(page.getByRole('status').filter({ hasText: 'Si existe una cuenta con este correo' })).toBeVisible()
  await page.goto('/login')
  await page.getByLabel('Correo electrónico', { exact: true }).fill(accounts.a.email)
  await page.getByLabel('Contraseña', { exact: true }).fill('password-123')
  await activate(page, page.getByRole('button', { name: 'Iniciar sesión', exact: true }))
  await expect(page.getByRole('link', { name: 'Datos de la cuenta', exact: true })).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('lang', 'es')
  await page.goto('/login')
  await expect(page.getByRole('heading', { name: 'Tu cuenta', exact: true })).toBeVisible()
  await captureReview(page, testInfo, 'spanish-account')
  await activate(page, page.getByRole('button', { name: 'Revisar importación de invitado', exact: true }))
  const dialog = page.getByRole('dialog', { name: '¿Importar planes de invitado a esta cuenta?', exact: true })
  await expect(dialog).toContainText('9 ejercicios, 0 rutinas y 0 entrenamientos completados.')
  await page.keyboard.press('Escape')
  await activate(page, page.getByRole('link', { name: 'Cambiar contraseña', exact: true }))
  await expect(page.getByLabel('Nueva contraseña', { exact: true })).toBeVisible()
  await activate(page, page.getByRole('button', { name: 'Guardar nueva contraseña', exact: true }))
  await expect(page.getByText('Usá al menos 8 caracteres.', { exact: true }).last()).toBeVisible()
  await activate(page, page.getByRole('button', { name: 'Continuar como invitado', exact: true }))
  await expect(page.getByRole('heading', { name: 'Tu entrenamiento, organizado', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Datos de la cuenta', exact: true })).toHaveCount(0)
  await expectNoOverflow(page)
})

async function signIn(page, account) {
  await page.goto('/login')
  await page.getByLabel('Email', { exact: true }).fill(account.email)
  await page.getByLabel('Password', { exact: true }).fill('password-123')
  await activate(page, page.getByRole('button', { name: 'Log in', exact: true }))
  await expect(page.getByRole('link', { name: 'Account data', exact: true })).toBeVisible()
  await expect(page.getByText(`${account.email} · Guest plans stay separate on this device.`, { exact: true })).toBeVisible()
}
async function uploadPixels(page) {
  const encoded = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = canvas.height = 4
    canvas.getContext('2d').fillRect(0, 0, 4, 4)
    return canvas.toDataURL('image/png').split(',')[1]
  })
  await page.locator('input[type=file]').setInputFiles({ name: 'cloud.png', mimeType: 'image/png', buffer: Buffer.from(encoded, 'base64') })
}

test('login validation/error, signup confirmation, recovery email, protected password page and guest continuation', async ({ page, context }, testInfo) => {
  const backend = await installProvider(context)
  await page.goto('/login')
  await expect(page.getByRole('heading', { name: 'Train with a plan', exact: true })).toBeVisible()
  await captureReview(page, testInfo, 'login')
  await activate(page, page.getByRole('button', { name: 'Log in', exact: true }))
  await expect(page.getByLabel('Email', { exact: true })).toBeFocused()
  await expect(page.getByLabel('Email', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByLabel('Email', { exact: true }).fill(accounts.a.email)
  await page.getByLabel('Password', { exact: true }).fill('wrong-password')
  await activate(page, page.getByRole('button', { name: 'Log in', exact: true }))
  await expect(page.getByRole('alert')).toContainText('Invalid login credentials')
  await expect(page.getByLabel('Password', { exact: true })).toHaveValue('wrong-password')
  await activate(page, page.getByRole('link', { name: 'Create an account', exact: true }))
  await expect(page.getByRole('heading', { name: 'Create your account', exact: true })).toBeVisible()
  await page.getByLabel('Email', { exact: true }).fill(accounts.b.email)
  await page.getByLabel('Password', { exact: true }).fill('password-123')
  await page.getByLabel('Confirm password', { exact: true }).fill('does-not-match')
  await activate(page, page.getByRole('button', { name: 'Create account', exact: true }))
  await expect(page.getByLabel('Confirm password', { exact: true })).toBeFocused()
  await expect(page.getByLabel('Confirm password', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByLabel('Confirm password', { exact: true }).fill('password-123')
  await activate(page, page.getByRole('button', { name: 'Create account', exact: true }))
  await expect(page.getByRole('status')).toContainText('Check your email to confirm your account')
  await expect(page.getByRole('link', { name: 'Account data', exact: true })).toHaveCount(0)
  await page.goto('/forgot-password')
  await page.getByLabel('Email', { exact: true }).fill(accounts.a.email)
  await activate(page, page.getByRole('button', { name: 'Send recovery email', exact: true }))
  await expect(page.getByRole('status')).toContainText('If an account uses this email')
  expect(backend.calls.find((call) => call.path === '/auth/v1/recover').redirect).toBe('http://127.0.0.1:4176/account/password')
  await captureReview(page, testInfo, 'recovery-email')
  await page.goto('/account/password')
  await expect(page.getByRole('heading', { name: 'Open your recovery link', exact: true })).toBeVisible()
  await activate(page, page.getByRole('link', { name: 'Continue as guest', exact: true }))
  await expect(page.getByRole('heading', { name: 'Rest day', exact: true })).toBeVisible()
  await expectNoOverflow(page)
})

test('guest copy requires approval; account images/history refresh on another device, stale/failed saves retain drafts, logout and accounts stay separate', async ({ page, context, browser }, testInfo) => {
  const backend = await installProvider(context)
  await page.clock.setFixedTime(new Date('2026-10-07T15:00:00Z'))
  await page.goto('/exercises/new')
  await page.getByLabel('Exercise name', { exact: true }).fill('Guest Curl')
  await page.getByLabel('Target muscle', { exact: true }).selectOption('Biceps')
  await activate(page, page.getByRole('button', { name: 'Create exercise', exact: true }))
  const routine = await createRoutine(page, 'Guest Plan', [3])
  await addAssignment(page, routine, 3, 'Guest Curl', { Sets: 2, Reps: 12, 'Target weight (kg)': 0 })
  await page.goto('/')
  await activate(page, page.getByRole('button', { name: 'Finish workout: Guest Plan', exact: true }))
  await expectProgress(page, 1, 1, 100)

  await signIn(page, accounts.a)
  await expect(page.getByRole('heading', { name: 'Rest day', exact: true })).toBeVisible()
  await expectProgress(page, 0, 0, null)
  await page.goto('/login')
  await activate(page, page.getByRole('button', { name: 'Review guest import', exact: true }))
  const dialog = page.getByRole('dialog', { name: 'Import guest plans into this account?', exact: true })
  await expect(dialog.getByRole('button', { name: 'Keep data separate', exact: true })).toBeFocused()
  await expect(dialog).toContainText('10 exercises, 1 routine, and 1 completed workout')
  await page.keyboard.press('Escape')
  expect(backend.rows.get(accounts.a.id).document.routines).toHaveLength(0)
  await activate(page, page.getByRole('button', { name: 'Review guest import', exact: true }))
  await captureReview(page, testInfo, 'import-confirmation')
  await activate(page, dialog.getByRole('button', { name: 'Import guest plans', exact: true }))
  await expect(page.getByRole('status')).toContainText('Guest plans imported')
  await expect(page.getByRole('button', { name: 'Review guest import', exact: true })).toBeFocused()
  expect(backend.rows.get(accounts.a.id).document.workoutLogs).toHaveLength(1)
  await activate(page, page.getByRole('button', { name: 'Review guest import', exact: true }))
  const beforeRetry = backend.rows.get(accounts.a.id).revision
  await activate(page, dialog.getByRole('button', { name: 'Import guest plans', exact: true }))
  await expect(dialog).not.toBeVisible()
  expect(backend.rows.get(accounts.a.id).revision).toBe(beforeRetry)
  await page.goto('/')
  await expectProgress(page, 1, 1, 100)

  await page.goto('/exercises/new')
  await page.getByLabel('Exercise name', { exact: true }).fill('Cloud Row')
  await page.getByLabel('Target muscle', { exact: true }).selectOption('Back')
  await uploadPixels(page)
  await activate(page, page.getByRole('button', { name: 'Create exercise', exact: true }))
  await expect(page.getByRole('link', { name: 'Edit Cloud Row', exact: true })).toBeVisible()
  const path = await page.getByRole('link', { name: 'Edit Cloud Row', exact: true }).getAttribute('href')
  expect(JSON.stringify(backend.rows.get(accounts.a.id).document)).not.toContain('data:image')
  expect(backend.objects.size).toBe(1)

  const second = await browser.newContext({ baseURL: 'http://127.0.0.1:4176', timezoneId: 'America/Argentina/Buenos_Aires' })
  try {
    await installProvider(second, backend)
    const other = await second.newPage()
    const errors = []
    other.on('pageerror', (error) => errors.push(error.message))
    await other.clock.setFixedTime(new Date('2026-10-07T15:00:00Z'))
    await signIn(other, accounts.a)
    await expectProgress(other, 1, 1, 100)
    await other.goto(path)
    await expect(other.getByLabel('Exercise name', { exact: true })).toHaveValue('Cloud Row')
    await expect.poll(() => other.getByAltText('Exercise preview').evaluate((image) => image.naturalWidth)).toBeGreaterThan(0)
    await page.goto(path)
    await page.getByLabel('Exercise name', { exact: true }).fill('First device draft')
    await other.getByLabel('Exercise name', { exact: true }).fill('Device two row')
    await activate(other, other.getByRole('button', { name: 'Save changes', exact: true }))
    await expect(other.getByRole('link', { name: 'Edit Device two row', exact: true })).toBeVisible()
    await activate(page, page.getByRole('button', { name: 'Save changes', exact: true }))
    await expect(page.getByLabel('Exercise name', { exact: true })).toHaveValue('First device draft')
    await expect(page.locator('.exercise-form [role=alert]')).toContainText('changed on another device')
    await expect(page.getByRole('button', { name: 'Reload page', exact: true })).toBeVisible()
    await activate(page, page.getByRole('button', { name: 'Reload page', exact: true }))
    await expect(page.getByLabel('Exercise name', { exact: true })).toHaveValue('Device two row')
    await page.getByLabel('Exercise name', { exact: true }).fill('Retry after error')
    backend.failSave = true
    await activate(page, page.getByRole('button', { name: 'Save changes', exact: true }))
    await expect(page.locator('.exercise-form [role=alert]')).toContainText('could not be confirmed')
    await expect(page.getByLabel('Exercise name', { exact: true })).toHaveValue('Retry after error')
    expect(backend.rows.get(accounts.a.id).document.exercises.at(-1).name).toBe('Device two row')
    backend.failSave = false
    await activate(page, page.getByRole('button', { name: 'Save changes', exact: true }))
    await expect(page.getByRole('link', { name: 'Edit Retry after error', exact: true })).toBeVisible()
    await page.goto('/login')
    backend.failLogout = true
    await activate(page, page.locator('.account-panel').getByRole('button', { name: 'Log out', exact: true }))
    await expect(page.getByRole('status')).toContainText('You are signed out on this browser')
    await expect(page.getByRole('link', { name: 'Account data', exact: true })).toHaveCount(0)
    await expect(page.getByLabel('Email', { exact: true })).toBeVisible()
    backend.failLogout = false
    await signIn(page, accounts.a)
    await page.goto('/login')
    await activate(page, page.locator('.account-panel').getByRole('button', { name: 'Log out', exact: true }))
    await expect(page.getByLabel('Email', { exact: true })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Account data', exact: true })).toHaveCount(0)
    await activate(page, page.getByRole('link', { name: 'Continue as guest', exact: true }))
    await expectProgress(page, 1, 1, 100)
    await page.goto('/exercises')
    await expect(page.getByRole('link', { name: 'Edit Guest Curl', exact: true })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Edit Retry after error', exact: true })).toHaveCount(0)
    await signIn(page, accounts.b)
    await expectProgress(page, 0, 0, null)
    await page.goto('/exercises')
    await expect(page.getByRole('link', { name: 'Edit Guest Curl', exact: true })).toHaveCount(0)
    await expect(page.getByRole('link', { name: 'Edit Retry after error', exact: true })).toHaveCount(0)
    await captureReview(page, testInfo, 'separate-account')
    expect(backend.rows.get(accounts.a.id).document.workoutLogs).toHaveLength(1)
    expect(backend.rows.get(accounts.b.id).document.workoutLogs).toHaveLength(0)
    expect(errors).toEqual([])
    await expectNoOverflow(page)
  } finally { await second.close() }
})

test('PKCE recovery callback authenticates password change; guest continuation signs out instead of showing account data', async ({ page, context }, testInfo) => {
  const backend = await installProvider(context)
  await page.clock.setFixedTime(new Date('2026-10-07T15:00:00Z'))
  await page.goto('/forgot-password')
  await page.getByLabel('Email', { exact: true }).fill(accounts.a.email)
  await activate(page, page.getByRole('button', { name: 'Send recovery email', exact: true }))
  await expect(page.getByRole('status')).toContainText('If an account uses this email')
  await page.goto('/account/password?code=recovery-code')
  await page.getByLabel('New password', { exact: true }).fill('new-password-123')
  await page.getByLabel('Confirm password', { exact: true }).fill('new-password-123')
  await activate(page, page.getByRole('button', { name: 'Save new password', exact: true }))
  await expect(page.getByRole('status')).toContainText('Your password has been updated')
  expect(backend.calls.some((call) => call.path === '/auth/v1/user' && call.method === 'PUT' && call.owner === accounts.a.id)).toBe(true)
  await captureReview(page, testInfo, 'new-password')
  await activate(page, page.getByRole('button', { name: 'Continue as guest', exact: true }))
  await expect(page.getByRole('link', { name: 'Account data', exact: true })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Rest day', exact: true })).toBeVisible()
  await expectNoOverflow(page)
})
