import { test, expect, activate, addAssignment, createRoutine, expectProgress, expectNoOverflow, captureReview } from './helpers.js'

test('exercise to completed workout, independent weekdays, order, refresh and preserved history', async ({ page }, testInfo) => {
  await page.clock.setFixedTime(new Date('2026-10-07T15:00:00Z'))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Rest day', exact: true })).toBeVisible()
  await expectProgress(page, 0, 0, null)

  await page.goto('/exercises/new')
  await activate(page, page.getByRole('button', { name: 'Create exercise', exact: true }))
  await expect(page.getByLabel('Exercise name', { exact: true })).toBeFocused()
  await expect(page.getByLabel('Exercise name', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByLabel('Exercise name', { exact: true }).fill('  Acceptance Cable  ')
  await page.getByLabel('Target muscle', { exact: true }).selectOption('Back')
  const png = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = 4; canvas.height = 4
    canvas.getContext('2d').fillRect(0, 0, 4, 4)
    return canvas.toDataURL('image/png').split(',')[1]
  })
  await page.locator('input[type=file]').setInputFiles({ name: 'exercise.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') })
  await expect(page.getByAltText('Exercise preview')).toBeVisible()
  await activate(page, page.getByRole('button', { name: 'Create exercise', exact: true }))
  await expect(page.getByText('Exercise created.', { exact: true })).toBeVisible()
  await page.getByLabel('Search exercises', { exact: true }).fill('  aCcEpTaNcE  ')
  await expect(page.getByRole('link', { name: 'Edit Acceptance Cable', exact: true })).toHaveCount(1)
  const exercisePath = await page.getByRole('link', { name: 'Edit Acceptance Cable', exact: true }).getAttribute('href')
  await page.goto(exercisePath)
  await expect(page.getByLabel('Exercise name', { exact: true })).toHaveValue('Acceptance Cable')
  await expect.poll(() => page.getByAltText('Exercise preview').evaluate((image) => image.naturalWidth)).toBeGreaterThan(0)

  const routinePath = await createRoutine(page, 'Acceptance Plan', [3, 5])
  await addAssignment(page, routinePath, 3, 'Acceptance Cable', { Sets: 4, Reps: 8, 'Target weight (kg)': 0 })
  await addAssignment(page, routinePath, 3, 'Bench Press', { Sets: 3, Reps: 12, 'Target weight (kg)': 60 })
  await addAssignment(page, routinePath, 3, 'Acceptance Cable', { Sets: 2, Reps: 15, 'Target weight (kg)': 20.25 })
  await activate(page, page.getByRole('button', { name: 'Move Bench Press, item 2, up', exact: true }))
  await expect(page.getByRole('button', { name: 'Move Bench Press, item 1, down', exact: true })).toBeFocused()
  await expect(page.locator('.assignment-row h3')).toHaveText(['Bench Press', 'Acceptance Cable', 'Acceptance Cable'])
  await page.reload()
  await expect(page.locator('.assignment-row h3')).toHaveText(['Bench Press', 'Acceptance Cable', 'Acceptance Cable'])

  const remove = page.getByRole('button', { name: 'Remove Acceptance Cable, item 3', exact: true })
  await activate(page, remove)
  const removal = page.getByRole('dialog', { name: 'Remove exercise from day?', exact: true })
  await expect(removal.getByRole('button', { name: 'Cancel', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(remove).toBeFocused()
  await expect(page.locator('.assignment-row')).toHaveCount(3)
  await activate(page, remove)
  await activate(page, removal.getByRole('button', { name: 'Remove assignment', exact: true }))
  await expect(page.locator('.assignment-row')).toHaveCount(2)

  await addAssignment(page, routinePath, 5, 'Acceptance Cable', { Sets: 3, Reps: 10, 'Target weight (kg)': 20.25 })
  await page.reload()
  await expect(page.getByRole('button', { name: 'Friday', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.assignment-row__targets')).toContainText('3 × 10')
  await expect(page.locator('.assignment-row__targets')).toContainText('20.25 kg')
  await activate(page, page.getByRole('button', { name: 'Wednesday', exact: true }))
  await expect(page.locator('.assignment-row__targets').nth(1)).toContainText('4 × 8')
  await activate(page, page.getByRole('link', { name: 'Edit targets for Acceptance Cable, item 2', exact: true }))
  await page.getByLabel('Sets', { exact: true }).fill('2.5')
  await activate(page, page.getByRole('button', { name: 'Save targets', exact: true }))
  await expect(page.getByLabel('Sets', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByLabel('Reps', { exact: true })).toHaveValue('8')
  await page.getByLabel('Sets', { exact: true }).fill('2')
  await page.getByLabel('Reps', { exact: true }).fill('14')
  await page.getByLabel('Target weight (kg)', { exact: true }).fill('0.25')
  await activate(page, page.getByRole('button', { name: 'Save targets', exact: true }))
  await expect(page.locator('.assignment-row__targets').nth(1)).toContainText('2 × 14')
  await activate(page, page.getByRole('button', { name: 'Friday', exact: true }))
  await expect(page.getByRole('region', { name: 'Friday', exact: true }).locator('.assignment-row__targets')).toContainText('3 × 10')
  await page.goBack()
  await expect(page.getByRole('button', { name: 'Wednesday', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.goForward()
  await expect(page.getByRole('button', { name: 'Friday', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expectNoOverflow(page)
  await captureReview(page, testInfo, 'configured-day')

  await activate(page, page.getByRole('link', { name: 'FORGE home', exact: true }))
  await expectProgress(page, 0, 2, 0)
  await expect(page.locator('.workout-exercise h4')).toHaveText(['Bench Press', 'Acceptance Cable'])
  await activate(page, page.getByRole('button', { name: 'Finish workout: Acceptance Plan', exact: true }))
  await expect(page.getByText('Workout completed and saved.', { exact: true })).toBeFocused()
  await expect(page.getByRole('button', { name: 'Completed workout: Acceptance Plan', exact: true })).toBeDisabled()
  await expectProgress(page, 1, 2, 50)
  await page.reload()
  await expectProgress(page, 1, 2, 50)
  await expect(page.locator('.weekday-strip [aria-current=date]')).toHaveAttribute('aria-label', /Completed\. 1 of 1 workouts completed/)
  await captureReview(page, testInfo, 'completed-workout')

  await page.goto(exercisePath)
  await page.getByLabel('Exercise name', { exact: true }).fill('Updated Cable')
  await activate(page, page.getByRole('button', { name: 'Save changes', exact: true }))
  await expect(page.getByRole('link', { name: 'Edit Updated Cable', exact: true })).toBeVisible()
  await page.goto(`${routinePath}?day=5`)
  await expect(page.locator('.assignment-row h3')).toHaveText(['Updated Cable'])
  await page.goto(exercisePath)
  await activate(page, page.getByRole('button', { name: 'Delete exercise', exact: true }))
  const deletion = page.getByRole('dialog', { name: 'Delete exercise?', exact: true })
  await expect(deletion).toContainText('removes 2 assignments')
  await activate(page, deletion.getByRole('button', { name: 'Cancel', exact: true }))
  await expect(page.getByLabel('Exercise name', { exact: true })).toHaveValue('Updated Cable')
  await activate(page, page.getByRole('button', { name: 'Delete exercise', exact: true }))
  await activate(page, deletion.getByRole('button', { name: 'Delete exercise', exact: true }))
  await expect(page.getByText('Exercise deleted.', { exact: true })).toBeVisible()
  await page.goto(`${routinePath}?day=5`)
  await expect(page.getByRole('heading', { name: 'No exercises for Friday yet', exact: true })).toBeVisible()
  await page.goto(routinePath)
  await activate(page, page.getByRole('button', { name: 'Delete routine', exact: true }))
  await activate(page, page.getByRole('dialog', { name: 'Delete routine?', exact: true }).getByRole('button', { name: 'Delete routine', exact: true }))
  await expect(page.getByText('Routine deleted.', { exact: true })).toBeVisible()
  await page.goto('/')
  await expectProgress(page, 1, 1, 100)
  await expect(page.locator('.workout-exercise h4')).toHaveText(['Bench Press', 'Acceptance Cable'])
  await expect(page.locator('.workout-exercise__targets').nth(1)).toContainText('2 × 14')
  await expect(page.locator('.workout-card')).toContainText('the original routine has been removed')
  await page.reload()
  await expectProgress(page, 1, 1, 100)
  await expectNoOverflow(page)
})
